apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdockerrepository-deployment
  labels:
    app: devopsdockerrepository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsdockerrepository
  template:
    metadata:
      labels:
        app: devopsdockerrepository
    spec:
      containers:
      - name: devopsdockerrepository
        image: devopsatulregistry.azurecr.io/devopsdockerrepository:latest 
        imagePullPolicy: IfNotPresent
        ports: 
           - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name: devopsdockerrepository-service
spec:
  type: LoadBalancer
  selector:
    app: devopsdockerrepository
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000
  